### ISSUE TITLE
申请证书-打开使用代理选项 Error: KeyID header contained an invalid account 

### ISSUE THREAD

**Issue by zhaoshunchen** [certd/certd#129]
## 一、问题描述
`申请证书-打开使用代理选项提示 Error: KeyID header contained an invalid account `

### 报错截图
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/31b69254-17ef-40ca-8259-9fb2c2565a08">

**Comment by zhaoshunchen** [comment]
如果关闭代理，也无法正常申请证书

> [2024-08-14T14:46:13.966] [ERROR] pipeline - [申请证书]<id:WHCFU0XswpalQjbcDljVB> [step] AxiosError [AggregateError]
    at AxiosError.from (/app/node_modules/.pnpm/axios@1.7.3_debug@4.3.6/node_modules/axios/dist/node/axios.cjs:873:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/.pnpm/axios@1.7.3_debug@4.3.6/node_modules/axios/dist/node/axios.cjs:3152:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.6_debug@4.3.6/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/app/node_modules/.pnpm/axios@1.7.3_debug@4.3.6/node_modules/axios/dist/node/axios.cjs:4262:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.request (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/http.js:81:22)
    at async HttpClient.getDirectory (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/http.js:99:26)
    at async HttpClient.getResourceUrl (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/http.js:156:21)
    at async AcmeApi.apiResourceRequest (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/api.js:73:29)
    at async AcmeClient.createOrder (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/client.js:296:22)
    at async module.exports (/app/node_modules/.pnpm/@certd+acme-client@1.22.6/node_modules/@certd/acme-client/src/auto.js:74:19)
    at async AcmeService.order (file:///app/node_modules/.pnpm/@certd+plugin-cert@1.23.1/node_modules/@certd/plugin-cert/dist/plugin/cert-plugin/acme.js:171:21)
    at async CertApplyPlugin.doCertApply (file:///app/node_modules/.pnpm/@certd+plugin-cert@1.23.1/node_modules/@certd/plugin-cert/dist/plugin/cert-plugin/index.js:64:26) {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 172.65.32.248:443
        at createConnectionError (node:net:1648:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1707:38)
        at listOnTimeout (node:internal/timers:583:11)
        at process.processTimers (node:internal/timers:519:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '172.65.32.248',
      port: 443
    },
    Error: connect ENETUNREACH 2606:4700:60:0:f53d:5624:85c7:3a2c:443 - Local (:::0)
        at internalConnectMultiple (node:net:1182:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
        at listOnTimeout (node:internal/timers:583:11)
        at process.processTimers (node:internal/timers:519:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2606:4700:60:0:f53d:5624:85c7:3a2c',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: 'http',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: null,
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/jose+json',
      'User-Agent': 'node-@certd/acme-client/1.22.6',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    acmeSettings: {
      httpChallengePort: 80,
      httpsChallengePort: 443,
      tlsAlpnChallengePort: 443
    },
    proxy: false,
    httpsAgent: null,
    url: 'https://acme-v02.api.letsencrypt.org/directory',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/directory',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'acme-v02.api.letsencrypt.org',
      port: '',
      agent: null,
      nativeProtocols: [Object],
      pathname: '/directory'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /directory HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/jose+json\r\n' +
        'User-Agent: node-@certd/acme-client/1.22.6\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: acme-v02.api.letsencrypt.org\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/directory',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'acme-v02.api.letsencrypt.org',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://acme-v02.api.letsencrypt.org/directory',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1118:18)
      at internalConnectMultiple (node:net:1186:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
      at listOnTimeout (node:internal/timers:583:11)
      at process.processTimers (node:internal/timers:519:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}

**Comment by greper** [comment]
1.24.0已修复
