### ISSUE TITLE
修改yaml配置进行admin密码重置无效

### ISSUE THREAD

**Issue by NickNameIsNull** [certd/certd#130]
## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
修改yaml配置文件：
![image](https://github.com/user-attachments/assets/ef50af6d-30e8-4996-a7f3-a308956fa359)

重启容器后，查看容器日志，未提示输出“重置1号管理员用户的密码完成”；

使用初始密码登录，也未登录成功。
```
root@cd-home-ubuntu-server:/data/docker-compose/certd# vi docker-compose.yaml 
root@cd-home-ubuntu-server:/data/docker-compose/certd# docker compose up -d
WARN[0000] /data/docker-compose/certd/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✔ Container certd  Started                                                                                               0.4s 
root@cd-home-ubuntu-server:/data/docker-compose/certd# docker logs -f --tail 500 certd

> @certd/ui-server@1.23.1 start
> cross-env NODE_ENV=production node ./bootstrap.js

[2024-08-16T19:57:34.309] [INFO] fast - load config development
[2024-08-16T19:57:34.310] [INFO] fast - load config production
[2024-08-16T19:57:34.311] [INFO] fast - load config production
[2024-08-16T19:57:34.311] [INFO] fast - load config preview
[2024-08-16T19:57:34.520] [INFO] default - 注册插件:plugin:CertApply
[2024-08-16T19:57:34.521] [INFO] default - 注册插件:plugin:CertApplyLego
[2024-08-16T19:57:34.521] [INFO] default - 注册插件:access:eab
[2024-08-16T19:57:34.547] [INFO] default - 注册插件:access:aliyun
[2024-08-16T19:57:34.559] [INFO] default - 注册插件:dnsProvider:aliyun
[2024-08-16T19:57:34.559] [INFO] default - 注册插件:plugin:DeployCertToAliyunCDN
[2024-08-16T19:57:34.657] [INFO] default - 注册插件:plugin:DeployCertToAliyunAckIngress
[2024-08-16T19:57:34.657] [INFO] default - 注册插件:plugin:uploadCertToAliyun
[2024-08-16T19:57:34.657] [INFO] default - 注册插件:access:dnspod
[2024-08-16T19:57:34.657] [INFO] default - 注册插件:access:tencent
[2024-08-16T19:57:34.818] [INFO] default - 注册插件:plugin:DeployCertToTencentCLB
[2024-08-16T19:57:34.819] [INFO] default - 注册插件:plugin:DeployCertToTencentTKEIngress
[2024-08-16T19:57:34.819] [INFO] default - 注册插件:plugin:DeployCertToTencentCDN
[2024-08-16T19:57:34.819] [INFO] default - 注册插件:plugin:UploadCertToTencent
[2024-08-16T19:57:34.819] [INFO] default - 注册插件:dnsProvider:dnspod
[2024-08-16T19:57:34.820] [INFO] default - 注册插件:access:ssh
[2024-08-16T19:57:34.830] [INFO] default - 注册插件:plugin:hostShellExecute
[2024-08-16T19:57:34.830] [INFO] default - 注册插件:plugin:uploadCertToHost
[2024-08-16T19:57:34.830] [INFO] default - 注册插件:access:huawei
[2024-08-16T19:57:34.831] [INFO] default - 注册插件:dnsProvider:huawei
[2024-08-16T19:57:34.831] [INFO] default - 注册插件:access:demo
[2024-08-16T19:57:34.831] [INFO] default - 注册插件:dnsProvider:demo
[2024-08-16T19:57:34.832] [INFO] default - 注册插件:plugin:demoTest
[2024-08-16T19:57:34.833] [INFO] default - 注册插件:access:cloudflare
[2024-08-16T19:57:34.836] [INFO] default - 注册插件:dnsProvider:cloudflare
[2024-08-16T19:57:34.837] [INFO] default - 注册插件:plugin:CloudflareDeployToCDN
[2024-08-16T19:57:34.839] [INFO] default - 注册插件:dnsProvider:tencent
[2024-08-16T19:57:34.885] [INFO] fast - 当前环境： production
[2024-08-16T19:57:34.891] [INFO] fast - 初始化站点开始
[2024-08-16T19:57:34.893] [INFO] fast - 初始化站点完成
[2024-08-16T19:57:34.893] [INFO] fast - 加载定时trigger开始
[2024-08-16T19:57:34.893] [INFO] fast - 加载定时trigger开始
[2024-08-16T19:57:34.894] [INFO] fast - 定时器数量： 0
2024-08-16 19:57:34.894 INFO 30 [midway:bootstrap] current app started
[2024-08-16T19:57:37.117] [INFO] fast - 请求开始: /api/login
[2024-08-16T19:57:37.117] [INFO] fast - 请求开始: /api/login
[2024-08-16T19:57:37.184] [ERROR] fast - 请求异常: /api/login 67ms CommonException: 用户名或密码错误
    at LoginService.login (file:///app/dist/modules/login/service/login-service.js:33:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LoginController.login (file:///app/dist/modules/login/controller/login-controller.js:22:23)
    at async Clz.<computed> (/app/node_modules/.pnpm/@midwayjs+core@3.16.2/node_modules/@midwayjs/core/dist/service/aspectService.js:92:34)
    at async /app/node_modules/.pnpm/@midwayjs+core@3.16.2/node_modules/@midwayjs/core/dist/common/webGenerator.js:43:26
    at async file:///app/dist/middleware/reset-passwd/middleware.js:25:13
    at async file:///app/dist/middleware/authority.js:38:17
    at async file:///app/dist/middleware/preview.js:20:17
    at async file:///app/dist/middleware/global-exception.js:17:17
    at async file:///app/dist/middleware/report.js:15:13 {
  status: 1
}

```

**Comment by greper** [comment]
文档写错了
应该是 `certd_system_resetAdminPasswd`
