### ISSUE TITLE
pipeline 执行失败 ValidateException: no id

### ISSUE THREAD

**Issue by h3110w0r1d-y** [certd/certd#135]
## 一、问题描述
版本v1.23.1

pipeline执行失败

### 复现步骤
1. 添加证书流水线
2. 手动触发
3. 前端空白，日志报pipeline执行失败

### 报错截图

![QQ_1724294463831](https://github.com/user-attachments/assets/e617fd99-911b-4eeb-8e95-e58c3deb0e44)

```
certd  | [2024-08-22T10:38:20.690] [INFO] fast - 请求开始: /api/pi/pipeline/trigger?id=1
certd  | [2024-08-22T10:38:20.691] [INFO] fast - 请求开始: /api/pi/pipeline/trigger?id=1
certd  | [2024-08-22T10:38:20.693] [INFO] fast - 用户手动启动job
certd  | [2024-08-22T10:38:20.698] [INFO] fast - 请求完成 /api/pi/pipeline/trigger?id=1 7ms
certd  | [2024-08-22T10:38:20.700] [INFO] fast - 请求完成: /api/pi/pipeline/trigger?id=1 200 9ms
certd  | [2024-08-22T10:38:20.732] [INFO] default - pipeline.undefined  start
certd  | [2024-08-22T10:38:20.733] [INFO] pipeline - [h3110w0r1d.com证书自动化]<id:undefined> [pipeline] 开始执行
certd  | [2024-08-22T10:38:20.735] [INFO] fast - 保存执行历史： 2
certd  | [2024-08-22T10:38:20.735] [ERROR] default - pipeline 执行失败 ValidateException: no id
certd  |     at PipelineService.update (file:///app/dist/basic/base-service.js:92:19)
certd  |     at PipelineService.update (file:///app/dist/modules/pipeline/service/pipeline-service.js:82:21)
certd  |     at Object.onChanged (file:///app/dist/modules/pipeline/service/pipeline-service.js:267:28)
certd  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
certd  |     at async Executor.onChanged (file:///app/node_modules/.pnpm/@certd+pipeline@1.23.1/node_modules/@certd/pipeline/dist/core/executor.js:25:13)
certd  |     at async Executor.runWithHistory (file:///app/node_modules/.pnpm/@certd+pipeline@1.23.1/node_modules/@certd/pipeline/dist/core/executor.js:70:9)
certd  |     at async Executor.run (file:///app/node_modules/.pnpm/@certd+pipeline@1.23.1/node_modules/@certd/pipeline/dist/core/executor.js:50:13)
certd  |     at async PipelineService.run (file:///app/dist/modules/pipeline/service/pipeline-service.js:286:13)
certd  |     at async Object.job (file:///app/dist/modules/pipeline/service/pipeline-service.js:170:21) {
certd  |   status: 10
certd  | }
```

#### 2. 实际效果
![QQ_1724294730398](https://github.com/user-attachments/assets/2ba5e907-8a79-47da-a872-79b0269d323a)

**Comment by yufajieluo** [comment]
同错误
