### ISSUE TITLE
K8S Ingress证书部署报错 V

### ISSUE THREAD

**Issue by superchaos** [certd/certd#177]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
K8S Ingress证书部署报错，k8s版本为1.23.10

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
任意自行部署的k8s服务都可以

### 报错截图
`请贴出报错日志截图`

**报错内容**
[2024-09-20T10:50:08.116] [ERROR] pipeline - [step] [K8S Ingress证书部署]<id:f7KbF0CBIbZrenMgNREVu> ： HttpError: HTTP request failed
    at Request._callback (/app/node_modules/.pnpm/@kubernetes+client-node@0.21.0/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:13642:36)
    at self.callback (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:185:22)

**请求头**
_header: 'PATCH /api/v1/namespaces/default/secrets/xxxxxxxx HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'host: xxxxxx:xxxx\r\n' +
        'content-type: application/json\r\n' +
        'content-length: 7116\r\n' +
        'Connection: close\r\n' +
        '\r\n',

**返回的结构体**
  body: {
    kind: 'Status',
    apiVersion: 'v1',
    metadata: {},
    status: 'Failure',
    message: '415: Unsupported Media Type',
    reason: 'UnsupportedMediaType',
    details: {},
    code: 415
  },

### 效果截图
`请贴出效果截图`

**Comment by greper** [comment]
1.25.4已支持
