### ISSUE TITLE
从 v1.25.x 更新至 v1.26.x 后面板前端无法正常打开

### ISSUE THREAD

**Issue by ImYrS** [certd/certd#207]
## 一、问题描述

部署方式为 docker compose，用 latest 更新以后发现无法访问。具体报错如下
<img width="467" alt="image" src="https://github.com/user-attachments/assets/25522452-1307-42bb-9ed4-39ab13f9c459">

后端报错如下
```
certd  | [2024-10-13T22:15:24.623] [INFO] default - 请求开始: /api/basic/settings/public
certd  | [2024-10-13T22:15:24.625] [ERROR] default - 请求异常: /api/basic/settings/public 2ms NotFoundError: /api/basic/settings/public Not Found
certd  |     at notFound (/app/node_modules/.pnpm/@midwayjs+koa@3.17.1/node_modules/@midwayjs/koa/dist/framework.js:135:23)
certd  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
certd  |     at async file:///app/dist/middleware/reset-passwd/middleware.js:25:13
certd  |     at async file:///app/dist/middleware/authority.js:35:17
certd  |     at async file:///app/dist/middleware/preview.js:20:17
certd  |     at async file:///app/dist/middleware/global-exception.js:17:17
certd  |     at async cors (/app/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:109:16)
certd  |     at async /app/node_modules/.pnpm/@midwayjs+i18n@3.17.3/node_modules/@midwayjs/i18n/dist/middleware.js:150:17
certd  |     at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
certd  |     at async session (/app/node_modules/.pnpm/@midwayjs+session@3.18.0/node_modules/@midwayjs/session/dist/middleware/session.js:137:17) {
certd  |   code: '404',
certd  |   cause: undefined,
certd  |   status: 404
certd  | }
certd  | [2024-10-13T22:15:24.627] [INFO] default - 请求开始: /api/mine/plusInfo
certd  | [2024-10-13T22:15:24.633] [ERROR] default - 请求异常: /api/mine/plusInfo 6ms NotFoundError: /api/mine/plusInfo Not Found
certd  |     at notFound (/app/node_modules/.pnpm/@midwayjs+koa@3.17.1/node_modules/@midwayjs/koa/dist/framework.js:135:23)
certd  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
certd  |     at async file:///app/dist/middleware/reset-passwd/middleware.js:25:13
certd  |     at async file:///app/dist/middleware/authority.js:35:17
certd  |     at async file:///app/dist/middleware/preview.js:20:17
certd  |     at async file:///app/dist/middleware/global-exception.js:17:17
certd  |     at async cors (/app/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:109:16)
certd  |     at async /app/node_modules/.pnpm/@midwayjs+i18n@3.17.3/node_modules/@midwayjs/i18n/dist/middleware.js:150:17
certd  |     at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
certd  |     at async session (/app/node_modules/.pnpm/@midwayjs+session@3.18.0/node_modules/@midwayjs/session/dist/middleware/session.js:137:17) {
certd  |   code: '404',
certd  |   cause: undefined,
certd  |   status: 404
certd  | }
```

用 latest 更新以后发现无法访问，依次按小版本从 v1.26.3 回退，发现回到 1.25.9 可正常使用。

### 复现步骤
从 v1.25.x 更新至 v1.26.x。数据库为 sqlite。

**Comment by ImYrS** [comment]
确认为 Nginx 反向代理缓存导致
