### ISSUE TITLE
西部数码的泛域名证书申请报错

### ISSUE THREAD

**Issue by UHoliday** [certd/certd#228]
[2024-10-30T14:21:04.923] [INFO] pipeline - HTTP request: post https://acme-v02.api.letsencrypt.org/acme/authz-v3/423124146817
[2024-10-30T14:21:05.661] [INFO] pipeline - RESP 200 post https://acme-v02.api.letsencrypt.org/acme/authz-v3/423124146817
[2024-10-30T14:21:14.061] [INFO] pipeline - 证书申请失败"Authentication failed"
[2024-10-30T14:21:14.062] [INFO] pipeline - 清理challenge痕迹，length:0
[2024-10-30T14:21:14.063] [ERROR] pipeline - [step] [申请证书]<id:PbXYlNYVozFxFzcWz4G8i> ： Error [unhandledRejectionError]: "Authentication failed"
    at WestDnsProvider.doRequestApi (file:///app/dist/plugins/plugin-west/dns-provider.js:43:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WestDnsProvider.createRecord (file:///app/dist/plugins/plugin-west/dns-provider.js:71:21)
    at async AcmeService.challengeCreateFn (file:///app/node_modules/.pnpm/@certd+plugin-cert@1.24.4/node_modules/@certd/plugin-cert/dist/plugin/cert-plugin/acme.js:132:20)
    at async Object.challengeCreateFn (file:///app/node_modules/.pnpm/@certd+plugin-cert@1.24.4/node_modules/@certd/plugin-cert/dist/plugin/cert-plugin/acme.js:219:24)
    at async challengeFunc (/app/node_modules/.pnpm/@certd+acme-client@1.24.4/node_modules/@certd/acme-client/src/auto.js:123:30)
    at async /app/node_modules/.pnpm/@certd+acme-client@1.24.4/node_modules/@certd/acme-client/src/auto.js:209:17

**Comment by greper** [comment]
普通域名没问题？

**Comment by greper** [comment]
普通域名没问题？
