### ISSUE TITLE
邮箱设置，。总是测试不成功。

### ISSUE THREAD

**Issue by 365v** [certd/certd#239]
搞不清是服务器拦截，还是 需要特殊的扩展
我用 qq邮箱， qq企业邮箱设置都不行

**Comment by greper** [comment]
报错截图

**Comment by greper** [comment]
https://certd.docmirror.cn/guide/use/email/

**Comment by 365v** [comment]
![1316d2a9-c72b-4152-90c3-827cb487dc4a](https://github.com/user-attachments/assets/e6018539-bf7b-4b08-bd79-27a29d6090d8)

**Comment by greper** [comment]
看看后台日志

**Comment by 365v** [comment]
[2024-11-14T20:41:42.372] [INFO] default - 请求开始: /api/sys/settings/saveEmailSettings
[2024-11-14T20:41:42.378] [INFO] default - 请求完成: /api/sys/settings/saveEmailSettings 6ms
[2024-11-14T20:41:50.796] [INFO] default - 请求开始: /api/pi/plugin/groups
[2024-11-14T20:41:50.800] [INFO] default - 请求完成: /api/pi/plugin/groups 4ms
[2024-11-14T20:41:50.802] [INFO] default - 请求开始: /api/pi/pipeline/detail?id=1
[2024-11-14T20:41:50.805] [INFO] default - 请求完成: /api/pi/pipeline/detail?id=1 3ms
[2024-11-14T20:41:50.889] [INFO] default - 请求开始: /api/pi/history/list
[2024-11-14T20:41:50.896] [INFO] default - 请求完成: /api/pi/history/list 7ms
[2024-11-14T20:41:50.981] [INFO] default - 请求开始: /api/pi/history/detail?id=3
[2024-11-14T20:41:50.987] [INFO] default - 请求完成: /api/pi/history/detail?id=3 6ms
[2024-11-14T20:41:51.312] [INFO] default - 请求开始: /api/pi/plugin/groups
[2024-11-14T20:41:51.316] [INFO] default - 请求完成: /api/pi/plugin/groups 4ms
[2024-11-14T20:41:51.318] [INFO] default - 请求开始: /api/pi/pipeline/detail?id=2
[2024-11-14T20:41:51.322] [INFO] default - 请求完成: /api/pi/pipeline/detail?id=2 4ms
[2024-11-14T20:41:54.888] [INFO] default - 请求开始: /api/sys/settings/getEmailSettings
[2024-11-14T20:41:54.892] [INFO] default - 请求完成: /api/sys/settings/getEmailSettings 4ms
[2024-11-14T20:42:01.222] [INFO] default - 请求开始: /api/sys/settings/getSysSettings
[2024-11-14T20:42:01.227] [INFO] default - 请求完成: /api/sys/settings/getSysSettings 5ms
[2024-11-14T20:42:03.310] [INFO] default - 请求开始: /api/sys/settings/getEmailSettings
[2024-11-14T20:42:03.313] [INFO] default - 请求完成: /api/sys/settings/getEmailSettings 3ms
[2024-11-14T20:42:04.159] [INFO] default - 请求开始: /api/pi/plugin/groups
[2024-11-14T20:42:04.164] [INFO] default - 请求完成: /api/pi/plugin/groups 5ms
[2024-11-14T20:42:04.167] [INFO] default - 请求开始: /api/pi/pipeline/detail?id=1
[2024-11-14T20:42:04.169] [INFO] default - 请求完成: /api/pi/pipeline/detail?id=1 2ms
[2024-11-14T20:42:05.624] [INFO] default - 请求开始: /api/pi/pipeline/page
[2024-11-14T20:42:05.629] [INFO] default - 请求完成: /api/pi/pipeline/page 5ms
[2024-11-14T20:42:05.630] [INFO] default - 请求开始: /api/pi/plugin/groups
[2024-11-14T20:42:05.632] [INFO] default - 请求完成: /api/pi/plugin/groups 2ms
[2024-11-14T20:42:05.634] [INFO] default - 请求开始: /api/pi/pipeline/page
[2024-11-14T20:42:05.638] [INFO] default - 请求完成: /api/pi/pipeline/page 4ms
[2024-11-14T20:42:06.592] [INFO] default - 请求开始: /api/mine/info
[2024-11-14T20:42:06.600] [INFO] default - 请求完成: /api/mine/info 8ms
[2024-11-14T20:42:06.669] [INFO] default - 请求开始: /api/statistic/count
[2024-11-14T20:42:06.677] [INFO] default - 请求完成: /api/statistic/count 8ms
[2024-11-14T20:42:06.782] [INFO] default - 请求开始: /api/pi/plugin/groups
[2024-11-14T20:42:06.785] [INFO] default - 请求完成: /api/pi/plugin/groups 3ms
[2024-11-14T21:24:46.461] [INFO] default - 请求开始: /api/pi/access/page
[2024-11-14T21:24:46.468] [INFO] default - 请求完成: /api/pi/access/page 7ms
[2024-11-14T21:24:46.469] [INFO] default - 请求开始: /api/pi/access/accessTypeDict
[2024-11-14T21:24:46.473] [INFO] default - 请求完成: /api/pi/access/accessTypeDict 4ms
[2024-11-14T21:24:46.473] [INFO] default - 请求开始: /api/pi/access/page
[2024-11-14T21:24:46.477] [INFO] default - 请求完成: /api/pi/access/page 4ms
[2024-11-14T21:24:50.182] [INFO] default - 请求开始: /api/sys/settings/getSysSettings
[2024-11-14T21:24:50.195] [INFO] default - 请求完成: /api/sys/settings/getSysSettings 13ms
[2024-11-14T21:24:51.313] [INFO] default - 请求开始: /api/sys/settings/getEmailSettings
[2024-11-14T21:24:51.317] [INFO] default - 请求完成: /api/sys/settings/getEmailSettings 4ms
[2024-11-14T21:25:08.768] [INFO] default - 请求开始: /api/basic/email/test
[2024-11-14T21:25:08.770] [INFO] default - sendEmail {
  userId: 1,
  receivers: [ '63@qq.com' ],
  subject: '测试邮件,from certd',
  content: '测试邮件,from certd'
}
[2024-11-14T21:27:08.800] [ERROR] default - 请求异常: /api/basic/email/test 120032ms Error: Connection timeout
    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.9.16/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
    at SMTPConnection._onError (/app/node_modules/.pnpm/nodemailer@6.9.16/node_modules/nodemailer/lib/smtp-connection/index.js:793:20)
    at Timeout.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.9.16/node_modules/nodemailer/lib/smtp-connection/index.js:237:22)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}

**Comment by greper** [comment]
certd什么版本

**Comment by 365v** [comment]
用的1panel的docker镜像拉取

**Comment by greper** [comment]
具体什么版本？

**Comment by greper** [comment]
证书可以申请成功?

**Comment by 365v** [comment]
https://certd.docmirror.cn/guide/install/1panel/  这个页面的，原封不动 搬过去了

**Comment by greper** [comment]
![image](https://github.com/user-attachments/assets/e01b281e-77b2-4327-ae28-3c0142c8b586)

**Comment by 365v** [comment]
Let's Encrypt证书可以正常申请。

**Comment by 365v** [comment]
![bf0687b86431162ce8deac4a3b5703c6](https://github.com/user-attachments/assets/0b128e77-e550-4625-b926-438ce6cf0f6a)

**Comment by greper** [comment]
ipv6服务器？

**Comment by greper** [comment]
![image](https://github.com/user-attachments/assets/a4a043a1-b84e-44ee-8b35-921ce5899040)

试试设置成这样

**Comment by 365v** [comment]
不行的，测试了。465端口 防火墙 也打开了

**Comment by 365v** [comment]
换了一台服务器。测试是正常的。 这台服务器不知道是屏蔽了465端口，还是其它缺组件

**Comment by 365v** [comment]
已经落实，是这个 服务器 屏蔽了465端口。

**Comment by greper** [comment]
ok，关闭issue了

**Comment by shoot82003** [comment]
方法:
npm config set strict-ssl false
465 是否ssl 是
忽略证书校验 否
即可
