### ISSUE TITLE
上传证书到主机 任务失败

### ISSUE THREAD

**Issue by qida** [certd/certd#3]
[root@VM_0_7_centos certd]# npm run certd

> certd-run@1.0.0 certd
> node index.js

[2022-01-06T18:50:14.189] [INFO] certd - ------------------- Cert-D ---------------------
[2022-01-06T18:50:14.194] [INFO] certd - 任务开始
[2022-01-06T18:50:14.194] [INFO] certd - 证书任务 ["*.xxx.com"] 开始
[2022-01-06T18:50:14.203] [INFO] certd - 证书还未过期： 2022-04-06T09:09:40.000Z ,剩余 89 天
[2022-01-06T18:50:14.204] [INFO] certd - 暂不更新证书
[2022-01-06T18:50:14.204] [INFO] certd - 证书任务 ["*.xxx.com"] 完成
[2022-01-06T18:50:14.204] [INFO] certd - 证书保存路径: /root/.certd/xxxx@foxmail.com/certs/_.xxx.com-54841215a878604fc0374157be69815b/2022.01.06.180944
[2022-01-06T18:50:14.204] [INFO] certd - ----------------------
[2022-01-06T18:50:14.204] [INFO] certd - 部署任务开始
[2022-01-06T18:50:14.205] [INFO] certd - ------------【D1-新部署流程】-----------
[2022-01-06T18:50:14.206] [INFO] certd - ----【上传证书到主机】开始执行
[2022-01-06T18:50:14.304] [INFO] certd - 连接服务器成功
[2022-01-06T18:50:14.359] [INFO] certd - 上传文件： {"localPath":"/root/.certd/xxx@foxmail.com/certs/_.xxx.com-54841215a878604fc0374157be69815b/2022.01.06.180944/_.xxx.com.crt","remotePath":"/root/ssl"}
执行命令：  mkdir -p /root
Client :: ready
[vm.xxxx.cn][close]:code:0
[2022-01-06T18:50:14.462] [ERROR] certd - 流程执行失败 Error: Failure
    at SFTPStream._transform (/mnt/certd/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at SFTPStream.Writable.write (node:internal/streams/writable:334:10)
    at Channel.ondata (node:internal/streams/readable:754:22)
    at Channel.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Channel.Readable.push (node:internal/streams/readable:228:10)
    at SSH2Stream.<anonymous> (/mnt/certd/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (node:events:390:28)
    at parsePacket (/mnt/certd/node_modules/ssh2-streams/lib/ssh.js:3191:10)
    at SSH2Stream._transform (/mnt/certd/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12) {
  code: 4,
  lang: ''
}
[2022-01-06T18:50:14.464] [INFO] certd -
[2022-01-06T18:50:14.465] [INFO] certd - 任务完成
[2022-01-06T18:50:14.465] [INFO] certd - ---------------------------任务结果总览--------------------------
[2022-01-06T18:50:14.465] [INFO] certd - 【更新证书】---------------------------------------    [skip]          还未到过期时间，跳过
[2022-01-06T18:50:14.465] [INFO] certd - 【D1-新部署流程】-----------------------------------   [error]         执行失败：Failure
[2022-01-06T18:50:14.465] [INFO] certd -    └【上传证书到主机】-------------------------------  [error]         Failure
[2022-01-06T18:50:14.466] [INFO] certd - 【result】---------------------------------------      [error]         D1-新部署流程执行失败：Failure
[2022-01-06T18:50:14.466] [INFO] certd - 【context】 {"certIsNew":false,"D1-新部署流程":{}}
[2022-01-06T18:50:14.466] [ERROR] certd - 任务执行出错 Error: D1-新部署流程执行失败：Failure
    at Executor.doRun (file:///mnt/certd/node_modules/@certd/executor/src/index.js:93:15)
    at async Executor.run (file:///mnt/certd/node_modules/@certd/executor/src/index.js:28:14)
    at async file:///mnt/certd/index.js:18:1
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: D1-新部署流程执行失败：Failure
    at Executor.doRun (file:///mnt/certd/node_modules/@certd/executor/src/index.js:93:15)
    at async Executor.run (file:///mnt/certd/node_modules/@certd/executor/src/index.js:28:14)
    at async file:///mnt/certd/index.js:18:1

域名及个人信息，已经做了隐藏。

**Comment by greper** [comment]
配置发出来看一下

**Comment by qida** [comment]
> 

options.json  
```json
{
    "cert": {
        "domains": [
            "*.xxx.com"
        ],
        "email": "xxx@foxmail.com",
        "dnsProvider": {
            "type": "aliyun",
            "accessProvider": "provider_1"
        },
        "ca": "LetEncrypt",
        "csr": {
            "country": "CN",
            "state": "ShanDong",
            "locality": "JiNan",
            "organization": "xxx",
            "organizationUnit": "IT Department"
        }
    },
    "accessProviders": {
        "provider_1": {
            "key": "provider_1",
            "name": "阿里云",
            "type": "aliyun",
            "accessKeyId": "xxx",
            "accessKeySecret": "xxx"
        },
        "provider_2": {
            "key": "provider_2",
            "name": "主机",
            "type": "ssh",
            "port": "2222",
            "username": "root",
            "host": "vm.xxx.cn",
            "password": "xxx"
        }
    },
    "deploy": [
        {
            "deployName": "D1-新部署流程",
            "_isEdit": false,
            "tasks": [
                {
                    "taskName": "上传证书到主机",
                    "type": "uploadCertToHost",
                    "_isAdd": false,
                    "props": {
                        "crtPath": "/root/ssl",
                        "keyPath": "/root/ssl",
                        "accessProvider": "provider_2"
                    }
                }
            ]
        }
    ]
}
```

**Comment by greper** [comment]
![image](https://user-images.githubusercontent.com/1687298/148476216-a8a2394a-1e30-43ee-bd3e-e9e47744724b.png)

**Comment by qida** [comment]
经改正上传成功。我的错误是：上传路径没有写全路径。非常感谢
