### ISSUE TITLE
前端生成的代码好像没更新, 目前申请acme-client报错signature algorithm not supported

### ISSUE THREAD

**Issue by mayongze** [certd/certd#5]
[2022-10-17T16:39:07.587] [ERROR] certd - 任务执行出错 Error: Error finalizing order :: signature algorithm not supported
    at AcmeApi.apiRequest (/root/certificate/certd-run/node_modules/@certd/acme-client/src/api.js:54:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AcmeClient.finalizeOrder (/root/certificate/certd-run/node_modules/@certd/acme-client/src/client.js:351:22)
    at async module.exports (/root/certificate/certd-run/node_modules/@certd/acme-client/src/auto.js:201:5)
    at async AcmeService.order (file:///root/certificate/certd-run/node_modules/@certd/certd/src/acme.js:155:17)
    at async Certd.doCertApply (file:///root/certificate/certd-run/node_modules/@certd/certd/src/index.js:60:18)
    at async Certd.certApply (file:///root/certificate/certd-run/node_modules/@certd/certd/src/index.js:54:12)
    at async Executor.runCertd (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:105:18)
    at async Executor.doRun (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:52:18)
    at async Executor.run (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:28:14)
    at async file:///root/certificate/certd-run/index.js:18:1
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Error finalizing order :: signature algorithm not supported
    at AcmeApi.apiRequest (/root/certificate/certd-run/node_modules/@certd/acme-client/src/api.js:54:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AcmeClient.finalizeOrder (/root/certificate/certd-run/node_modules/@certd/acme-client/src/client.js:351:22)
    at async module.exports (/root/certificate/certd-run/node_modules/@certd/acme-client/src/auto.js:201:5)
    at async AcmeService.order (file:///root/certificate/certd-run/node_modules/@certd/certd/src/acme.js:155:17)
    at async Certd.doCertApply (file:///root/certificate/certd-run/node_modules/@certd/certd/src/index.js:60:18)
    at async Certd.certApply (file:///root/certificate/certd-run/node_modules/@certd/certd/src/index.js:54:12)
    at async Executor.runCertd (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:105:18)
    at async Executor.doRun (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:52:18)
    at async Executor.run (file:///root/certificate/certd-run/node_modules/@certd/executor/src/index.js:28:14)
    at async file:///root/certificate/certd-run/index.js:18:1

**Comment by greper** [comment]
已更新

**Comment by mayongze** [comment]
前段打不开啦, Not Found

**Comment by greper** [comment]
这回好了。准备做一个支持本地部署带ui的服务，现在这个先凑合用着先

**Comment by mayongze** [comment]
好啦
