### ISSUE TITLE
1.20.16 泛域名申请失败！Cloudflare

### ISSUE THREAD

**Issue by captainstdin** [certd/certd#76]
> 感谢您支持certd，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/certd/certd/issues)

## 一、问题描述
泛域名申请失败！Cloudflare，版本`1.20.16`

### 复现步骤
设置好 cloudflare dns密钥，申请 *.api.xxx.com 证书

### 报错截图
```
[2024-07-02T21:35:01.820] [INFO] pipeline - HTTP request: post https://acme-v02.api.letsencrypt.org/acme/chall-v3/371731731227/-NSiWQ
[2024-07-02T21:35:02.463] [INFO] pipeline - RESP 200 post https://acme-v02.api.letsencrypt.org/acme/chall-v3/371731731227/-NSiWQ
[2024-07-02T21:35:02.464] [INFO] pipeline - Item has status: invalid
[2024-07-02T21:35:02.467] [INFO] pipeline - [auto] [api.打码信息.com] challengeCreateFn threw error: No TXT record found at _acme-challenge.打码信息.com
[2024-07-02T21:35:08.278] [INFO] pipeline - 证书申请失败
[2024-07-02T21:35:08.279] [INFO] pipeline - Error [unhandledRejectionError]: No TXT record found at _acme-challenge.打码信息.com
    at verifyFn (/app/node_modules/@certd/acme-client/src/client.js:560:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retryPromise (/app/node_modules/@certd/acme-client/src/util.js:54:22)
    at async challengeFunc (/app/node_modules/@certd/acme-client/src/auto.js:144:17)
    at async /app/node_modules/@certd/acme-client/src/auto.js:171:9
[2024-07-02T21:35:08.279] [INFO] pipeline - 清理challenge痕迹，length:1
```

**Comment by greper** [comment]
多试几次

**Comment by captainstdin** [comment]
试了N次还是不行，这是什么情况。 域名在cloudflare申请的也是cloudflare API

我看了日志，好像顺序不对，好像是  删除了TXT记录后 再去let's Encrpt api申请 *.aa.com 的

**Comment by captainstdin** [comment]
目前我使用 acme.sh 暂时申请下来使用了

**Comment by FiendFEARing** [comment]
好像是有问题，我今天新增一个域名按之前成功的配置，也出现了一样的报错。

Update：多跑了几次，终于成功了

**Comment by greper** [comment]
1.21.0 已优化，升级再试试

**Comment by captainstdin** [comment]
好的，我试试
